media:
  input: public
  output: /

content:
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    fields:
      - name: title
        type: string
      - name: date
        type: date
      - name: category
        type: string
      - name: description
        type: string
      - name: draft
        type: boolean
      - name: body
        type: rich-text

  - name: game
    label: Game
    type: collection
    path: src/content/game
    fields:
      - name: title
        type: string
      - name: date
        type: date
      - name: category
        type: string
      - name: description
        type: string
      - name: draft
        type: boolean
      - name: links
        type: object
        list: true
        fields:
          - name: label
            type: string
          - name: href
            type: string
          - name: external
            type: boolean
          - name: description
            type: string
      - name: body
        type: rich-text

  - name: creation
    label: Creation
    type: collection
    path: src/content/creation
    fields:
      - name: title
        type: string
      - name: date
        type: date
      - name: category
        type: string
      - name: description
        type: string
      - name: draft
        type: boolean
      - name: links
        type: object
        list: true
        fields:
          - name: label
            type: string
          - name: href
            type: string
          - name: external
            type: boolean
          - name: description
            type: string
      - name: body
        type: rich-text

  - name: lily
    label: Lily
    type: collection
    path: src/content/lily
    fields:
      - name: title
        type: string
      - name: date
        type: date
      - name: category
        type: string
      - name: description
        type: string
      - name: draft
        type: boolean
      - name: links
        type: object
        list: true
        fields:
          - name: label
            type: string
          - name: href
            type: string
          - name: external
            type: boolean
          - name: description
            type: string
      - name: body
        type: rich-text

  - name: text
    label: Text
    type: collection
    path: src/content/text
    fields:
      - name: title
        type: string
      - name: date
        type: date
      - name: category
        type: string
      - name: description
        type: string
      - name: draft
        type: boolean
      - name: links
        type: object
        list: true
        fields:
          - name: label
            type: string
          - name: href
            type: string
          - name: external
            type: boolean
          - name: description
            type: string
      - name: body
        type: rich-text
